ALTER TABLE public.canchas
  ADD COLUMN IF NOT EXISTS venue_id UUID REFERENCES public.venues(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;
CREATE INDEX IF NOT EXISTS canchas_venue_idx ON public.canchas (venue_id) WHERE venue_id IS NOT NULL;
-- DOWN: ALTER TABLE public.canchas DROP COLUMN IF EXISTS venue_id, DROP COLUMN IF EXISTS lat, DROP COLUMN IF EXISTS lng;
